### ISSUE TITLE
About frequency discriminator

### ISSUE THREAD

**Issue by Yablon** [rishikksh20/TFGAN#2]
Hi, the time loss calculated by convolution layer is very impressive. 
I have questions about [frequency discriminator](https://github.com/rishikksh20/TFGAN/blob/main/model/freq_discriminator.py#L148)

As we know, the output of discriminators are supposed to be real or fake labels for input waves. Your frequency discriminator seems to get [B, channels, T] shape output. Does that obey the rule of discriminator or there is something more I can learn from ? 
Thank you !

**Comment by Yablon** [comment]
@rishikksh20 hi, I close this due to lack of attention here.

**Comment by rishikksh20** [comment]
@Yablon When we dealing with audio domain, least squares(LSGAN) loss works better than real and fake audio. Check out MelGAN paper and https://arxiv.org/abs/1611.04076 .
