### ISSUE TITLE
[Question] Upsample in generator net

### ISSUE THREAD

**Issue by OnceJune** [rishikksh20/TFGAN#3]
Hi, thanks for your code. I found in the generator net, the implement used a reflection padding before  calling conv1d when processing upsample, which is not mentioned in the paper.

> Then in addition to using transpose convolution, we also repeat the output of the first step by the up-sample factor directly and following a convolutional layer.

My question is why this reflection padding is necessary? Thanks in advance.

**Comment by rishikksh20** [comment]
@OnceJune perform better than normal padding before Conv1d
