### ISSUE TITLE
Feature matching loss bug?

### ISSUE THREAD

**Issue by alexdemartos** [rishikksh20/TFGAN#7]
https://github.com/rishikksh20/TFGAN/blob/8c377705365da4144f1668e33c54939b2b5240c6/utils/train.py#L124

Shouldn't `disc_fake` be `disc_fake_g`?

**Comment by rishikksh20** [comment]
yes, still I will check on my local implementation.

**Comment by alexdemartos** [comment]
Solved in last commit
